* Changed ToDoItem's `created', `modified', and `completed' fields from   longs to Instants.  Changed its `due' field from Long to LocalDate. * Implemented MockToDoRepository, MockToDoCursor, and ToDoRepositoryTests. * Fixed missing SELECT columns in the todo table query in ToDoRepositoryImpl. * Fixed a duplicate insert bug in ToDoRepositoryImpl.insertCategory. * Fixed null check bugs with the "due" and   "completed" columns in ToDoCursorImpl. * Downgraded desugar_jdk_libs to fix a NoClassDefFoundError   error with j$.util.DesugarCollections. * Upgraded the espresso-core library from 2.2.2 to 3.4.0.